In [47]:
import pandas as pd
import numpy as np

In [48]:
DATA_DIR = '/Users/Rambo/Downloads/highschool_data/'

SUBJECT = ['yuwen','shuxue','yingyu','tongyongjishu','wuli','huaxue','shengwu','zhengzhi','lishi','dili']

COLUMNS = {"试题编号","参考学生数","得分人数","得分率","平均分","难度","标准差","斯皮尔曼区分度","皮尔顺区分度","A等平均分","B等平均分","C等平均分","D等平均分"}

RANK_MAP = {"dili":"Dlfd","yuwen":"Ywfd","huaxue":"Hxfd","lishi":"Lsfd","shengwu":"Swfd","wuli":"Wlfd",
            "zhengzhi":"Zzfd","tiyu":"Tyfd","shuxue":"Sxfd","yingyu":"Yyfd","xxjs":"xxjsfd"}

SUBJECT_MAP = {"dili":"地理","yuwen":"语文","huaxue":"化学","lishi":"历史","shengwu":"生物","wuli":"物理",
            "zhengzhi":"政治","tiyu":"体育","shuxue":"数学","yingyu":"英语","xxjs":"信息技术"}

subject = "shuxue"

In [49]:
dfrank = pd.read_csv(DATA_DIR+"等级数据.txt",delimiter="\t")
dfitem = pd.read_csv(DATA_DIR+subject+"ItemInfor.csv")
dfoption = pd.read_csv(DATA_DIR+subject+"Options.txt",delimiter="\t")
#筛选参加考试人数
dfoption = dfoption.loc[dfoption["absent"]=="N"]

INDICES = dfitem.loc[dfitem["tilei"]=="客观题"]["shitihao"].tolist()

    
columns = ["参考学生人数","A选项人数", "B选项人数", "C选项人数", "D选项人数", "AB选项人数", "AC选项人数", "AD选项人数", "BC选项人数",
               "BD选项人数", "CD选项人数", "ABC选项人数", "ABD选项人数", "ACD选项人数", "BCD选项人数", "ABCD选项人数", "#选项人数",
               "A选项%", "B选项%", "C选项%", "D选项%", "AB选项%", "AC选项%", "AD选项%", "BC选项%", "BD选项%",
               "CD选项%", "ABC选项%", "ABD选项%", "ACD选项%", "BCD选项%", "ABCD选项%", "#选项%"]

INDICES

['k01',
 'k02',
 'k03',
 'k04',
 'k05',
 'k06',
 'k07',
 'k08',
 'k09',
 'k10',
 'k11',
 'k12',
 'k13',
 'k14',
 'k15',
 'k16',
 'k17',
 'k18',
 'k19',
 'k20',
 'k21',
 'k22',
 'k23',
 'k24',
 'k25',
 'k26',
 'k27',
 'k28',
 'k29',
 'k30',
 'k31',
 'k32',
 'k33',
 'k34',
 'k35']

In [50]:
#参考学生总数
realExaminee = dfoption[INDICES].count()
df1 = pd.DataFrame(realExaminee,index=INDICES,columns=["参考学生人数"])

In [51]:
#arrs = [object]*len(INDICES)
arrs = [dfoption[index].value_counts() for index in INDICES]
arrs

[B     286965
 D      20526
 C       2622
 A        968
 #        148
 BD         8
 AB         2
 Name: k01, dtype: int64, A     253368
 B      48737
 C       6624
 D       2200
 #        213
 AD        74
 BD        10
 AC         7
 AB         4
 BC         2
 Name: k02, dtype: int64, D     289568
 C      14231
 B       4249
 A       2733
 #        339
 BD        74
 AD        34
 CD         7
 AC         2
 AB         1
 BC         1
 Name: k03, dtype: int64, B     249521
 A      27142
 C      26284
 D       7550
 #        717
 BD        13
 BC         8
 AC         2
 CD         1
 AD         1
 Name: k04, dtype: int64, C     239175
 B      41075
 D      16609
 A      13843
 #        511
 BC         8
 AD         5
 AC         5
 CD         3
 BD         3
 AB         2
 Name: k05, dtype: int64, B     282149
 C      17078
 A       6378
 D       5490
 #        125
 BD         7
 AB         5
 BC         3
 AD         2
 AC         2
 Name: k06, dtype: int64, A     228180
 B      61709
 C      11953
 D       8857
 #        477
 AC        40
 AD        11
 BD         5
 BC         4
 AB         2
 CD         1
 Name: k07, dtype: int64, C     254518
 D      28060
 A      23193
 B       5058
 #        374
 AC        11
 AD         9
 CD         5
 BD         5
 BC         4
 AB         2
 Name: k08, dtype: int64, B     282247
 A      12526
 C      10473
 D       5636
 #        333
 BD        11
 BC         7
 AB         3
 AC         3
 Name: k09, dtype: int64, A     259432
 C      22059
 D      15192
 B      13793
 #        724
 AD        17
 AB         9
 AC         9
 CD         2
 BD         2
 Name: k10, dtype: int64, A     227974
 B      50817
 C      16067
 D      16020
 #        313
 AD        27
 AC        10
 AB         5
 BD         3
 CD         2
 BC         1
 Name: k11, dtype: int64, D     231717
 B      39305
 C      26876
 A      12943
 #        290
 BD        48
 CD        29
 AD        25
 BC         4
 AB         1
 AC         1
 Name: k12, dtype: int64, C       208797
 B        49552
 D        34200
 A        17679
 #          972
 BD          13
 AD           7
 CD           6
 BC           6
 AC           5
 AB           1
 ABCD         1
 Name: k13, dtype: int64, B     213037
 C      57275
 D      33077
 A       7216
 #        542
 BD        54
 AD        11
 BC        11
 CD        10
 AC         5
 AB         1
 Name: k14, dtype: int64, D     284426
 C       9985
 A       9825
 B       6481
 #        399
 BD        57
 CD        35
 AD        25
 AC         4
 AB         1
 BC         1
 Name: k15, dtype: int64, C     258602
 B      25433
 D      17768
 A       8942
 #        470
 CD         5
 AC         5
 BD         5
 AD         4
 BC         4
 AB         1
 Name: k16, dtype: int64, B     234502
 D      59487
 C       9787
 A       6762
 #        642
 BD        44
 AD         7
 BC         3
 CD         2
 AC         2
 AB         1
 Name: k17, dtype: int64, D     294203
 B      11073
 C       2836
 A       2728
 #        262
 BD        59
 AD        53
 CD        18
 BC         3
 AB         2
 AC         2
 Name: k18, dtype: int64, A     203460
 C      66814
 B      20590
 D      19010
 #       1315
 AC        24
 AD        12
 CD         6
 BD         4
 BC         3
 AB         1
 Name: k19, dtype: int64, C     301415
 A       3540
 B       3299
 D       2525
 #        404
 AC        34
 BC         8
 CD         6
 AB         3
 BD         3
 AD         2
 Name: k20, dtype: int64, B     141690
 A     129588
 D      22007
 C      17401
 #        512
 BD        14
 AC        10
 AD         9
 BC         4
 AB         3
 CD         1
 Name: k21, dtype: int64, C     250485
 B      34445
 A      19740
 D       5992
 #        532
 CD        18
 BD        10
 AD         6
 BC         6
 AC         5
 Name: k22, dtype: int64, D     273744
 A      14634
 B      11771
 C      10457
 #        536
 AD        54
 BD        26
 CD         9
 AC         6
 AB         2
 Name: k23, dtype: int64, A     255557
 D      36115
 B      10610
 C       8208
 #        643
 AD        52
 AC        32
 BD        12
 CD         5
 AB         4
 BC         1
 Name: k24, dtype: int64, C     187493
 A      42288
 D      41872
 B      38875
 #        632
 AC        43
 AD        14
 CD         8
 BD         8
 AB         4
 BC         2
 Name: k25, dtype: int64, B     224231
 D      41785
 C      33440
 A      11249
 #        483
 BD        19
 AD        15
 AC         7
 CD         6
 BC         4
 Name: k26, dtype: int64, D     190487
 C      99579
 B      15907
 A       4761
 #        439
 BD        27
 CD        19
 AD        11
 AC         6
 BC         2
 AB         1
 Name: k27, dtype: int64, B     244073
 D      35478
 C      16798
 A      14371
 #        437
 BD        45
 AD        11
 BC         9
 CD         8
 AB         5
 AC         4
 Name: k28, dtype: int64, D     232336
 A      37666
 B      27328
 C      13452
 #        367
 BD        48
 AD        25
 CD        11
 AC         3
 BC         2
 AB         1
 Name: k29, dtype: int64, D     225383
 C      42893
 B      33696
 A       8270
 #        906
 AD        35
 BD        30
 CD        16
 AC         8
 AB         1
 BC         1
 Name: k30, dtype: int64, A      200525
 B       49315
 C       45731
 D       14901
 #         718
 AC         21
 AD          7
 BD          7
 AB          6
 BC          5
 CD          2
 ACD         1
 Name: k31, dtype: int64, C     265687
 A      24352
 B      16453
 D       4358
 #        329
 AC        35
 BC        14
 AD         5
 BD         4
 AB         2
 Name: k32, dtype: int64, A     137121
 B     132534
 C      25929
 D      14986
 #        577
 BD        28
 AC        27
 AD        21
 CD         6
 BC         6
 AB         4
 Name: k33, dtype: int64, C       96203
 B       82011
 A       66358
 D       65612
 #         986
 BD         19
 AD         17
 AC         12
 CD          9
 BC          8
 AB          2
 ABCD        2
 Name: k34, dtype: int64, C       113528
 D        86224
 B        74256
 A        35349
 #         1752
 BD          37
 AD          35
 AC          27
 CD          20
 BC           8
 AB           2
 ABCD         1
 Name: k35, dtype: int64]

In [52]:
#columns = ["A","B","C","D","AB","AC","AD","BC","BD","CD","ABC","ABD","ACD","BCD","ABCD","#"]
df2_columns = {"A":"A选项人数", "B":"B选项人数","C":"C选项人数", "D":"D选项人数", "AB":"AB选项人数", "AC":"AC选项人数","AD": "AD选项人数","BC": "BC选项人数",
               "BD":"BD选项人数", "CD":"CD选项人数", "ABC":"ABC选项人数","ABD":"ABD选项人数","ACD": "ACD选项人数","BCD":"BCD选项人数","ABCD":"ABCD选项人数","#": "#选项人数"}
df2 = pd.concat(arrs,axis = 1,join = 'outer',sort=True).T

In [45]:
df3 = df2.div(realExaminee[0]).mul(100)
df2.rename(columns=df2_columns,inplace=True)
# 求得百分比  &3
df3_columns = {"A": "A选项%", "B": "B选项%", "C": "C选项%", "D": "D选项%","AB": "AB选项%","AC": "AC选项%","AD": "AD选项%","BC": "BC选项%",
               "BD": "BD选项%","CD": "CD选项%","ABC": "ABC选项%","ABD": "ABD选项%","ACD": "ACD选项%","BCD": "BCD选项%","ABCD": "ABCD选项%","#":"#选项%"}
df3.rename(columns=df3_columns,inplace=True)
#构造最终DataFrame
dflist = [df1, df2, df3]
#检测KeyError异常 缺哪列 补上
df = pd.concat(dflist, axis=1, join="inner")
print(df)

     参考学生人数  #选项人数     A选项人数  AB选项人数  ABC选项人数  ABCD选项人数  ABD选项人数  AC选项人数  \
k01  311814  368.0  100831.0     2.0      NaN       NaN      NaN     4.0
k02  311814  268.0  251676.0     4.0      NaN       NaN      NaN    17.0
k03  311814  224.0   40679.0     NaN      NaN       NaN      NaN    10.0
k04  311814  246.0    7522.0     NaN      NaN       NaN      NaN     1.0
k05  311814  687.0   29407.0     NaN      NaN       NaN      NaN     3.0
k06  311814  532.0  104259.0     1.0      NaN       NaN      NaN     4.0
k07  311814  478.0  173345.0     3.0      NaN       NaN      NaN    15.0
k08  311814  190.0   29353.0     1.0      NaN       NaN      NaN    23.0
k09  311814  744.0   61387.0     4.0      NaN       NaN      NaN     7.0
k10  311814  298.0   37162.0     8.0      NaN       NaN      NaN     7.0
k11  311814  163.0   37102.0     NaN      NaN       NaN      NaN     5.0
k12  311814  262.0   12066.0     NaN      NaN       NaN      NaN     3.0
k13  311814  502.0  175868.0     4.0      1.0       NaN      NaN    19.0
k14  311814  773.0   57301.0     NaN      NaN       NaN      NaN    17.0
k15  311814  376.0   28847.0     NaN      NaN       NaN      NaN     8.0
k16  311814  269.0    5655.0     3.0      NaN       NaN      NaN     2.0
k17  311814  632.0   55107.0     3.0      NaN       NaN      NaN     9.0
k18  311814  504.0   82589.0     6.0      NaN       NaN      NaN    15.0
k19  311814  760.0   98328.0     2.0      NaN       NaN      NaN    20.0
k20  311814  364.0   30375.0     4.0      NaN       NaN      NaN    10.0
k21  311814  457.0  171110.0     8.0      NaN       NaN      NaN    10.0
k22  311814  729.0   59414.0     3.0      NaN       NaN      NaN     4.0
k23  311814  217.0    3481.0     1.0      NaN       NaN      NaN     1.0
k24  311814  260.0  234531.0     2.0      NaN       NaN      NaN    19.0
k25  311814  193.0  188272.0     6.0      1.0       NaN      2.0    14.0
k26  311814  214.0    6390.0     1.0      NaN       NaN      NaN     3.0
k27  311814  254.0    6680.0     NaN      NaN       NaN      NaN     3.0
k28  311814  259.0   28236.0     NaN      1.0       NaN      NaN     3.0
k29  311814  295.0   14978.0     1.0      NaN       1.0      NaN     1.0
k30  311814  356.0   15046.0     2.0      NaN       1.0      NaN     2.0
k31  311814  219.0    5418.0     3.0      NaN       NaN      NaN     2.0
k32  311814  267.0    2462.0     NaN      NaN       NaN      NaN    18.0
k33  311814  526.0  123717.0     4.0      NaN       NaN      NaN    12.0
k34  311814  441.0   35991.0     5.0      NaN       NaN      NaN    10.0
k35  311814  361.0   21807.0     5.0      NaN       NaN      NaN     5.0

     AD选项人数     B选项人数  ...    ABD选项%     AC选项%     AD选项%       B选项%     BC选项%  \
k01     7.0   44547.0  ...       NaN  0.001283  0.002245  14.286402       NaN
k02     7.0   26491.0  ...       NaN  0.005452  0.002245   8.495770  0.000641
k03     7.0   27808.0  ...       NaN  0.003207  0.002245   8.918137  0.000962
k04    12.0    2418.0  ...       NaN  0.000321  0.003848   0.775462  0.000962
k05    10.0   55122.0  ...       NaN  0.000962  0.003207  17.677846  0.000321
k06    17.0   60824.0  ...       NaN  0.001283  0.005452  19.506501  0.000321
k07     7.0   26915.0  ...       NaN  0.004811  0.002245   8.631748  0.000641
k08     4.0    6293.0  ...       NaN  0.007376  0.001283   2.018190  0.000321
k09     6.0    8239.0  ...       NaN  0.002245  0.001924   2.642280  0.001604
k10    13.0  195800.0  ...       NaN  0.002245  0.004169  62.793845  0.002566
k11     1.0   44772.0  ...       NaN  0.001604  0.000321  14.358560  0.000962
k12     6.0  134524.0  ...       NaN  0.000962  0.001924  43.142386  0.001924
k13    37.0   36949.0  ...       NaN  0.006093  0.011866  11.849692  0.001283
k14    18.0   49873.0  ...       NaN  0.005452  0.005773  15.994471  0.001283
k15    25.0   10643.0  ...       NaN  0.002566  0.008018   3.413253  0.000962
k16    13.0  182095.0  ...       NaN  0.000641  0.004169  58.398597       NaN
k17    12.0   74860.0  ...       NaN  0.002886  0.003848  24.007902  0.000962
k18    14.0   27440.0  ...       NaN  0.004811  0.004490   8.800118  0.001604
k19     9.0  122569.0  ...       NaN  0.006414  0.002886  39.308370  0.003207
k20    13.0   53175.0  ...       NaN  0.003207  0.004169  17.053436  0.001924
k21    29.0   52550.0  ...       NaN  0.003207  0.009300  16.852996  0.000321
k22    24.0  107537.0  ...       NaN  0.001283  0.007697  34.487547  0.000321
k23    47.0    9669.0  ...       NaN  0.000321  0.015073   3.100887       NaN
k24    24.0   42612.0  ...       NaN  0.006093  0.007697  13.665839       NaN
k25    40.0   16874.0  ...  0.000641  0.004490  0.012828   5.411559       NaN
k26     5.0   77030.0  ...       NaN  0.000962  0.001604  24.703830  0.000321
k27    11.0   38974.0  ...       NaN  0.000962  0.003528  12.499118  0.000321
k28     4.0   40708.0  ...       NaN  0.000962  0.001283  13.055219  0.001604
k29    19.0    4368.0  ...       NaN  0.000321  0.006093   1.400835  0.000962
k30     6.0  241027.0  ...       NaN  0.000641  0.001924  77.298325  0.000641
k31    38.0    6696.0  ...       NaN  0.000641  0.012187   2.147434  0.000321
k32     3.0   28306.0  ...       NaN  0.005773  0.000962   9.077848  0.004169
k33    30.0   43422.0  ...       NaN  0.003848  0.009621  13.925609  0.000962
k34    32.0   21811.0  ...       NaN  0.003207  0.010263   6.994875  0.001924
k35     7.0  221970.0  ...       NaN  0.001604  0.002245  71.186669  0.002245

       BCD选项%     BD选项%       C选项%     CD选项%       D选项%
k01       NaN  0.000962   5.259546  0.000321  47.993676
k02       NaN  0.000321   3.895271  0.000641   6.798925
k03       NaN  0.001283  76.756015  0.004169   1.196226
k04       NaN  0.004490  18.579987  0.006093  78.137608
k05       NaN  0.004490  25.499176  0.003848  47.158883
k06       NaN  0.002566   7.975267  0.000962  38.900434
k07       NaN  0.003207  20.386192  0.000321  15.224140
k08       NaN  0.000962  88.118879  0.001283   0.376827
k09       NaN  0.002245  59.470389  0.000641  17.951728
k10       NaN  0.005452   5.480832  0.003207  19.691547
k11       NaN  0.000641  66.856203  0.000641   6.830033
k12       NaN  0.005131  38.832124  0.001604  14.060305
k13       NaN  0.009300   8.582039  0.002245  22.973311
k14       NaN  0.003528  34.467343  0.003848  30.893738
k15       NaN  0.004811  50.461493  0.005452  36.731513
k16       NaN  0.009621   2.168921  0.003207  37.514031
k17       NaN  0.005131  26.608491  0.002566  31.491530
k18       NaN  0.003207  55.814684  0.001924   8.718980
k19       NaN  0.001604  21.212967  0.000962   7.685030
k20       NaN  0.006414  53.181704  0.002566  19.887176
k21       NaN  0.001283  13.298312  0.002245  14.807546
k22       NaN  0.005773  22.052249  0.000321  24.155747
k23       NaN  0.015714   1.039722  0.006093  94.635905
k24       NaN  0.004169   2.176939  0.000321   8.839885
k25  0.000321  0.001924  21.517956  0.002566  12.603988
k26  0.000321  0.007376   9.674036  0.003207  63.490093
k27       NaN  0.006093  37.094871  0.001604  48.169742
k28       NaN  0.002245  73.363608  0.004490   4.431809
k29       NaN  0.025336   1.776700  0.005452  91.885547
k30       NaN  0.010904   4.038626  0.000641  13.707851
k31       NaN  0.008659   6.941318  0.008338  89.072332
k32       NaN  0.001604  88.920639  0.001604   1.112202
k33       NaN  0.005452  18.878883  0.004490  27.324623
k34       NaN  0.020846  25.262176  0.006735  56.014483
k35       NaN  0.009621  16.079778  0.004169   5.602699

[35 rows x 31 columns]