In [1]:
import pandas as pd
import numpy as np

In [6]:

DATA_DIR = '/Users/Rambo/Downloads/highschool_data/'
DATA_OUTPUT_DIR = "/Users/Rambo/Documents/GZ_output/"

SUBJECT = ['yuwen','shuxue','yingyu','tongyongjishu','wuli','huaxue','shengwu','zhengzhi','lishi','dili']

COLUMNS = {"试题编号","参考学生数","得分人数","得分率","平均分","难度","标准差","斯皮尔曼区分度","皮尔顺区分度","A等平均分","B等平均分","C等平均分","D等平均分"}

RANK_MAP = {"dili":"Dlfd","yuwen":"Ywfd","huaxue":"Hxfd","lishi":"Lsfd","shengwu":"Swfd","wuli":"Wlfd",
            "zhengzhi":"Zzfd","tiyu":"Tyfd","shuxue":"Sxfd","yingyu":"Yyfd","xxjs":"xxjsfd"}

SUBJECT_MAP = {"dili":"地理","yuwen":"语文","huaxue":"化学","lishi":"历史","shengwu":"生物","wuli":"物理",
            "zhengzhi":"政治","tiyu":"体育","shuxue":"数学","yingyu":"英语","xxjs":"信息技术"}

CITY_MAP = {1:"贵阳",2:"遵义",3:"安顺",4:"毕节",5:"铜仁",6:"六盘水",7:"黔南州",8:"黔东南",9:"黔西南"}

def dirToString(subject,type):
    typeToDir={
        "item":DATA_DIR+subject+'ItemInfor.csv',
        "score":DATA_DIR+subject+'Score.txt',
        "rank":DATA_DIR+"等级数据.txt",
        "option":DATA_DIR+subject+"Options.txt"
    }
    return typeToDir.get(type)

subject = "dili"

In [60]:
dfscore = pd.read_csv(dirToString(subject,"score"),delimiter='\t')
#fullscore
dfitem = pd.read_csv(dirToString(subject,"item"))
fullscore = dfitem.loc[dfitem["shitihao"]=="totalScore"]["full"].iloc[0]
#noabsent
dfscore_noabsent = dfscore.loc[dfscore["absent"]=="N"]
#index
begin = np.linspace(0,140,15).tolist()
end = np.linspace(10,150,15).tolist()
#考虑到满分不在[140,150)
series_city_fullscore = dfscore_noabsent.loc[(dfscore_noabsent["totalScore"] == fullscore)].groupby("cityID")["absent"].count().rename("满分")
series_list = [dfscore_noabsent.loc[(dfscore_noabsent["totalScore"] >= i) & (dfscore_noabsent["totalScore"] <j) ].groupby("cityID")["absent"].count().rename("["+str(np.int(i))+","+str(np.int(j))+")") for i,j in zip(begin,end)]
series_list = series_list+[series_city_fullscore]
df_scoreRange = pd.concat(series_list,axis=1,join="outer").fillna(0).applymap(int)
#df_scoreRange
#series_city_fullscore
#求比例 先统计各市州总人数
series_totalExaminee = dfscore_noabsent.groupby("cityID")["kh"].count()
#比率表
df_scoreRangeRate = df_scoreRange.div(series_totalExaminee,axis=0).mul(100)
df_scoreRangeRate.columns = [column+"%" for column in df_scoreRangeRate.columns]
#CITYMAP
series_city_name = pd.Series(CITY_MAP,name="区域名称")
pd.concat([series_city_name,df_scoreRange,df_scoreRangeRate],axis=1)

,区域名称,"[0,10)","[10,20)","[20,30)","[30,40)","[40,50)","[50,60)","[60,70)","[70,80)","[80,90)",...,"[60,70)%","[70,80)%","[80,90)%","[90,100)%","[100,110)%","[110,120)%","[120,130)%","[130,140)%","[140,150)%",满分%
1,贵阳,3,1,1,9,27,130,460,1019,2201,...,1.541607,3.414994,7.376253,12.577499,18.888032,21.602601,19.916887,11.769831,2.305707,0.033513
2,遵义,8,0,7,31,145,731,2384,5806,9989,...,4.118511,10.030232,17.256630,21.824307,20.647836,14.435519,7.354237,2.368489,0.367971,0.003455
3,安顺,1,0,1,26,69,267,822,1723,2799,...,5.121814,10.735871,17.440339,19.714624,18.026045,13.720481,8.442894,4.018942,0.510935,0.000000
4,毕节,4,2,9,50,318,1174,3509,8007,12909,...,5.287505,12.065276,19.451811,23.351516,19.368935,11.989934,4.852028,1.176843,0.109999,0.000000
5,铜仁,10,1,14,70,226,706,1997,4230,6904,...,5.348868,11.329851,18.492032,21.789206,19.276818,13.011919,6.318468,1.591000,0.091067,0.000000
6,六盘水,2,2,5,19,62,336,1087,2606,4626,...,3.891037,9.328465,16.559278,21.194874,20.912085,15.363688,8.311856,2.584479,0.325745,0.003580
7,黔南州,3,0,4,27,102,293,986,2378,4318,...,3.784738,9.127898,16.574543,21.411024,21.660525,15.603409,7.508061,2.464302,0.214955,0.003838
8,黔东南,4,1,1,13,40,156,489,1550,3320,...,1.550461,4.914550,10.526650,17.451409,22.990583,21.268905,14.210977,5.599417,0.805352,0.000000
9,黔西南,9,1,5,27,130,465,1233,2701,4231,...,5.027523,11.013252,17.251784,20.538226,19.926606,13.418960,7.070336,2.682977,0.468909,0.004077