In [38]:
import pandas as pd
import numpy as np

In [39]:
DATA_DIR = '/Users/Rambo/Downloads/highschool_data/'

SUBJECT = ['yuwen','shuxue','yingyu','tongyongjishu','wuli','huaxue','shengwu','zhengzhi','lishi','dili']

COLUMNS = {"试题编号","参考学生数","得分人数","得分率","平均分","难度","标准差","斯皮尔曼区分度","皮尔顺区分度","A等平均分","B等平均分","C等平均分","D等平均分"}

RANK_MAP = {"dili":"Dlfd","yuwen":"Ywfd","huaxue":"Hxfd","lishi":"Lsfd","shengwu":"Swfd","wuli":"Wlfd",
            "zhengzhi":"Zzfd","tiyu":"Tyfd","shuxue":"Sxfd","yingyu":"Yyfd","xxjs":"xxjsfd"}

SUBJECT_MAP = {"dili":"地理","yuwen":"语文","huaxue":"化学","lishi":"历史","shengwu":"生物","wuli":"物理",
            "zhengzhi":"政治","tiyu":"体育","shuxue":"数学","yingyu":"英语","xxjs":"信息技术"}

subject = "yuwen"

In [40]:
dfrank = pd.read_csv(DATA_DIR+"等级数据.txt",delimiter="\t")
dfitem = pd.read_csv(DATA_DIR+subject+"ItemInfor.csv")
dfoption = pd.read_csv(DATA_DIR+subject+"Options.txt",delimiter="\t")
#筛选参加考试人数
dfoption = dfoption.loc[dfoption["absent"]=="N"]

INDICES = dfitem.loc[dfitem["tilei"]=="客观题"]["shitihao"].tolist()

    
columns = ["参考学生人数","A选项人数", "B选项人数", "C选项人数", "D选项人数", "AB选项人数", "AC选项人数", "AD选项人数", "BC选项人数",
               "BD选项人数", "CD选项人数", "ABC选项人数", "ABD选项人数", "ACD选项人数", "BCD选项人数", "ABCD选项人数", "#选项人数",
               "A选项%", "B选项%", "C选项%", "D选项%", "AB选项%", "AC选项%", "AD选项%", "BC选项%", "BD选项%",
               "CD选项%", "ABC选项%", "ABD选项%", "ACD选项%", "BCD选项%", "ABCD选项%", "#选项%"]

INDICES

['k01',
 'k02',
 'k03',
 'k04',
 'k05',
 'k06',
 'k07',
 'k08',
 'k09',
 'k10',
 'k11',
 'k12',
 'k13',
 'k14',
 'k15',
 'k16',
 'k17',
 'k18',
 'k19',
 'k20',
 'k21',
 'k22',
 'k23',
 'k24',
 'k25',
 'k26',
 'k27',
 'k28',
 'k29',
 'k30',
 'k31',
 'k32',
 'k33',
 'k34',
 'k35']

In [41]:
#参考学生总数
realExaminee = dfoption[INDICES].count()
df1 = pd.DataFrame(realExaminee,index=INDICES,columns=["参考学生人数"])

In [42]:
#arrs = [object]*len(INDICES)
arrs = [dfoption[index].value_counts() for index in INDICES]
arrs

[D     149651
 A     100831
 B      44547
 C      16400
 #        368
 AD         7
 AC         4
 BD         3
 AB         2
 CD         1
 Name: k01, dtype: int64, A     251676
 B      26491
 D      21200
 C      12146
 #        268
 AC        17
 AD         7
 AB         4
 CD         2
 BC         2
 BD         1
 Name: k02, dtype: int64, C     239336
 A      40679
 B      27808
 D       3730
 #        224
 CD        13
 AC        10
 AD         7
 BD         4
 BC         3
 Name: k03, dtype: int64, D     243644
 C      57935
 A       7522
 B       2418
 #        246
 CD        19
 BD        14
 AD        12
 BC         3
 AC         1
 Name: k04, dtype: int64, D     147048
 C      79510
 B      55122
 A      29407
 #        687
 BD        14
 CD        12
 AD        10
 AC         3
 BC         1
 Name: k05, dtype: int64, D     121297
 A     104259
 B      60824
 C      24868
 #        532
 AD        17
 BD         8
 AC         4
 CD         3
 AB         1
 BC         1
 Name: k06, dtype: int64, A     173345
 C      63567
 D      47471
 B      26915
 #        478
 AC        15
 BD        10
 AD         7
 AB         3
 BC         2
 CD         1
 Name: k07, dtype: int64, C     274767
 A      29353
 B       6293
 D       1175
 #        190
 AC        23
 CD         4
 AD         4
 BD         3
 AB         1
 BC         1
 Name: k08, dtype: int64, C     185437
 A      61387
 D      55976
 B       8239
 #        744
 AC         7
 BD         7
 AD         6
 BC         5
 AB         4
 CD         2
 Name: k09, dtype: int64, B     195800
 D      61401
 A      37162
 C      17090
 #        298
 BD        17
 AD        13
 CD        10
 AB         8
 BC         8
 AC         7
 Name: k10, dtype: int64, C     208467
 B      44772
 A      37102
 D      21297
 #        163
 AC         5
 BC         3
 CD         2
 BD         2
 AD         1
 Name: k11, dtype: int64, B     134524
 C     121084
 D      43842
 A      12066
 #        262
 BD        16
 AD         6
 BC         6
 CD         5
 AC         3
 Name: k12, dtype: int64, A      175868
 D       71634
 B       36949
 C       26760
 #         502
 AD         37
 BD         29
 AC         19
 CD          7
 AB          4
 BC          4
 ABC         1
 Name: k13, dtype: int64, C     107474
 D      96331
 A      57301
 B      49873
 #        773
 AD        18
 AC        17
 CD        12
 BD        11
 BC         4
 Name: k14, dtype: int64, C     157346
 D     114534
 A      28847
 B      10643
 #        376
 AD        25
 CD        17
 BD        15
 AC         8
 BC         3
 Name: k15, dtype: int64, B     182095
 D     116974
 C       6763
 A       5655
 #        269
 BD        30
 AD        13
 CD        10
 AB         3
 AC         2
 Name: k16, dtype: int64, D     98195
 C     82969
 B     74860
 A     55107
 #       632
 BD       16
 AD       12
 AC        9
 CD        8
 AB        3
 BC        3
 Name: k17, dtype: int64, C     174038
 A      82589
 B      27440
 D      27187
 #        504
 AC        15
 AD        14
 BD        10
 CD         6
 AB         6
 BC         5
 Name: k18, dtype: int64, B     122569
 A      98328
 C      66145
 D      23963
 #        760
 AC        20
 BC        10
 AD         9
 BD         5
 CD         3
 AB         2
 Name: k19, dtype: int64, C     165828
 D      62011
 B      53175
 A      30375
 #        364
 BD        20
 AD        13
 AC        10
 CD         8
 BC         6
 AB         4
 Name: k20, dtype: int64, A     171110
 B      52550
 D      46172
 C      41466
 #        457
 AD        29
 AC        10
 AB         8
 CD         7
 BD         4
 BC         1
 Name: k21, dtype: int64, B     107537
 D      75321
 C      68762
 A      59414
 #        729
 AD        24
 BD        18
 AC         4
 AB         3
 CD         1
 BC         1
 Name: k22, dtype: int64, D     295088
 B       9669
 A       3481
 C       3242
 #        217
 BD        49
 AD        47
 CD        19
 AB         1
 AC         1
 Name: k23, dtype: int64, A     234531
 B      42612
 D      27564
 C       6788
 #        260
 AD        24
 AC        19
 BD        13
 AB         2
 CD         1
 Name: k24, dtype: int64, A      188272
 C       67096
 D       39301
 B       16874
 #         193
 AD         40
 AC         14
 CD          8
 AB          6
 BD          6
 ABD         2
 ABC         1
 BCD         1
 Name: k25, dtype: int64, D      197971
 B       77030
 C       30165
 A        6390
 #         214
 BD         23
 CD         10
 AD          5
 AC          3
 AB          1
 BCD         1
 BC          1
 Name: k26, dtype: int64, D     150200
 C     115667
 B      38974
 A       6680
 #        254
 BD        19
 AD        11
 CD         5
 AC         3
 BC         1
 Name: k27, dtype: int64, C      228758
 B       40708
 A       28236
 D       13819
 #         259
 CD         14
 BD          7
 BC          5
 AD          4
 AC          3
 ABC         1
 Name: k28, dtype: int64, D       286512
 A        14978
 C         5540
 B         4368
 #          295
 BD          79
 AD          19
 CD          17
 BC           3
 AB           1
 AC           1
 ABCD         1
 Name: k29, dtype: int64, B       241027
 D        42743
 A        15046
 C        12593
 #          356
 BD          34
 AD           6
 CD           2
 AB           2
 AC           2
 BC           2
 ABCD         1
 Name: k30, dtype: int64, D     277740
 C      21644
 B       6696
 A       5418
 #        219
 AD        38
 BD        27
 CD        26
 AB         3
 AC         2
 BC         1
 Name: k31, dtype: int64, C     277267
 B      28306
 D       3468
 A       2462
 #        267
 AC        18
 BC        13
 CD         5
 BD         5
 AD         3
 Name: k32, dtype: int64, A     123717
 D      85202
 C      58867
 B      43422
 #        526
 AD        30
 BD        17
 CD        14
 AC        12
 AB         4
 BC         3
 Name: k33, dtype: int64, D     174661
 C      78771
 A      35991
 B      21811
 #        441
 BD        65
 AD        32
 CD        21
 AC        10
 BC         6
 AB         5
 Name: k34, dtype: int64, B     221970
 C      50139
 A      21807
 D      17470
 #        361
 BD        30
 CD        13
 AD         7
 BC         7
 AB         5
 AC         5
 Name: k35, dtype: int64]

In [44]:
#columns = ["A","B","C","D","AB","AC","AD","BC","BD","CD","ABC","ABD","ACD","BCD","ABCD","#"]
df2_columns = {"A":"A选项人数", "B":"B选项人数","C":"C选项人数", "D":"D选项人数", "AB":"AB选项人数", "AC":"AC选项人数","AD": "AD选项人数","BC": "BC选项人数",
               "BD":"BD选项人数", "CD":"CD选项人数", "ABC":"ABC选项人数","ABD":"ABD选项人数","ACD": "ACD选项人数","BCD":"BCD选项人数","ABCD":"ABCD选项人数","#": "#选项人数"}
df2 = pd.concat(arrs,axis = 1,join = 'outer',sort=True).T

c:\python37\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.

In [21]:
df3 = df2.div(realExaminee[0]).mul(100)
df2.rename(columns=df2_columns,inplace=True)
# 求得百分比  &3
df3_columns = {"A": "A选项%", "B": "B选项%", "C": "C选项%", "D": "D选项%","AB": "AB选项%","AC": "AC选项%","AD": "AD选项%","BC": "BC选项%",
               "BD": "BD选项%","CD": "CD选项%","ABC": "ABC选项%","ABD": "ABD选项%","ACD": "ACD选项%","BCD": "BCD选项%","ABCD": "ABCD选项%","#":"#选项%"}
df3.rename(columns=df3_columns,inplace=True)
#构造最终DataFrame
dflist = [df1, df2, df3]
#检测KeyError异常 缺哪列 补上
df = pd.concat(dflist, axis=1, join="inner")
print(df)

              参考学生人数    0.0  0.5   1.0   1.5   2.0  2.5  3.0  3.5  4.0  ...  \
objectScore   311814   85.0  NaN   NaN   NaN   NaN  NaN  1.0  NaN  NaN  ...
subjectScore  311814  281.0  4.0  15.0  16.0  23.0  4.0  1.0  4.0  8.0  ...
totalScore    311814   75.0  1.0   NaN   NaN   NaN  NaN  1.0  NaN  NaN  ...
k01           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k02           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k03           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k04           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k05           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k06           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k07           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k08           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k09           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k10           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k11           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k12           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k13           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k14           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k15           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k16           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k17           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k18           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k19           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k20           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k21           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k22           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k23           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k24           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k25           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k26           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k27           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k28           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k29           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k30           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k31           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k32           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...
k33           311814    NaN  NaN   NaN   NaN   NaN  NaN  NaN  NaN  NaN  ...

               ABD选项人数    AC选项人数    AD选项人数      B选项人数    BC选项人数   BCD选项人数  \
objectScore        NaN       NaN       NaN        NaN       NaN       NaN
subjectScore       NaN       NaN       NaN        NaN       NaN       NaN
totalScore         NaN       NaN       NaN        NaN       NaN       NaN
k01                NaN  0.001283  0.002245  14.286402       NaN       NaN
k02                NaN  0.005452  0.002245   8.495770  0.000641       NaN
k03                NaN  0.003207  0.002245   8.918137  0.000962       NaN
k04                NaN  0.000321  0.003848   0.775462  0.000962       NaN
k05                NaN  0.000962  0.003207  17.677846  0.000321       NaN
k06                NaN  0.001283  0.005452  19.506501  0.000321       NaN
k07                NaN  0.004811  0.002245   8.631748  0.000641       NaN
k08                NaN  0.007376  0.001283   2.018190  0.000321       NaN
k09                NaN  0.002245  0.001924   2.642280  0.001604       NaN
k10                NaN  0.002245  0.004169  62.793845  0.002566       NaN
k11                NaN  0.001604  0.000321  14.358560  0.000962       NaN
k12                NaN  0.000962  0.001924  43.142386  0.001924       NaN
k13                NaN  0.006093  0.011866  11.849692  0.001283       NaN
k14                NaN  0.005452  0.005773  15.994471  0.001283       NaN
k15                NaN  0.002566  0.008018   3.413253  0.000962       NaN
k16                NaN  0.000641  0.004169  58.398597       NaN       NaN
k17                NaN  0.002886  0.003848  24.007902  0.000962       NaN
k18                NaN  0.004811  0.004490   8.800118  0.001604       NaN
k19                NaN  0.006414  0.002886  39.308370  0.003207       NaN
k20                NaN  0.003207  0.004169  17.053436  0.001924       NaN
k21                NaN  0.003207  0.009300  16.852996  0.000321       NaN
k22                NaN  0.001283  0.007697  34.487547  0.000321       NaN
k23                NaN  0.000321  0.015073   3.100887       NaN       NaN
k24                NaN  0.006093  0.007697  13.665839       NaN       NaN
k25           0.000641  0.004490  0.012828   5.411559       NaN  0.000321
k26                NaN  0.000962  0.001604  24.703830  0.000321  0.000321
k27                NaN  0.000962  0.003528  12.499118  0.000321       NaN
k28                NaN  0.000962  0.001283  13.055219  0.001604       NaN
k29                NaN  0.000321  0.006093   1.400835  0.000962       NaN
k30                NaN  0.000641  0.001924  77.298325  0.000641       NaN
k31                NaN  0.000641  0.012187   2.147434  0.000321       NaN
k32                NaN  0.005773  0.000962   9.077848  0.004169       NaN
k33                NaN  0.003848  0.009621  13.925609  0.000962       NaN

                BD选项人数      C选项人数    CD选项人数      D选项人数
objectScore        NaN        NaN       NaN        NaN
subjectScore       NaN        NaN       NaN        NaN
totalScore         NaN        NaN       NaN        NaN
k01           0.000962   5.259546  0.000321  47.993676
k02           0.000321   3.895271  0.000641   6.798925
k03           0.001283  76.756015  0.004169   1.196226
k04           0.004490  18.579987  0.006093  78.137608
k05           0.004490  25.499176  0.003848  47.158883
k06           0.002566   7.975267  0.000962  38.900434
k07           0.003207  20.386192  0.000321  15.224140
k08           0.000962  88.118879  0.001283   0.376827
k09           0.002245  59.470389  0.000641  17.951728
k10           0.005452   5.480832  0.003207  19.691547
k11           0.000641  66.856203  0.000641   6.830033
k12           0.005131  38.832124  0.001604  14.060305
k13           0.009300   8.582039  0.002245  22.973311
k14           0.003528  34.467343  0.003848  30.893738
k15           0.004811  50.461493  0.005452  36.731513
k16           0.009621   2.168921  0.003207  37.514031
k17           0.005131  26.608491  0.002566  31.491530
k18           0.003207  55.814684  0.001924   8.718980
k19           0.001604  21.212967  0.000962   7.685030
k20           0.006414  53.181704  0.002566  19.887176
k21           0.001283  13.298312  0.002245  14.807546
k22           0.005773  22.052249  0.000321  24.155747
k23           0.015714   1.039722  0.006093  94.635905
k24           0.004169   2.176939  0.000321   8.839885
k25           0.001924  21.517956  0.002566  12.603988
k26           0.007376   9.674036  0.003207  63.490093
k27           0.006093  37.094871  0.001604  48.169742
k28           0.002245  73.363608  0.004490   4.431809
k29           0.025336   1.776700  0.005452  91.885547
k30           0.010904   4.038626  0.000641  13.707851
k31           0.008659   6.941318  0.008338  89.072332
k32           0.001604  88.920639  0.001604   1.112202
k33           0.005452  18.878883  0.004490  27.324623

[36 rows x 599 columns]